# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import audio_pb2 as audio__pb2


class AudioGenerationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAudio = channel.unary_unary(
                '/AudioGenerationService/GenerateAudio',
                request_serializer=audio__pb2.Requirement.SerializeToString,
                response_deserializer=audio__pb2.Audio.FromString,
                )


class AudioGenerationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioGenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAudio,
                    request_deserializer=audio__pb2.Requirement.FromString,
                    response_serializer=audio__pb2.Audio.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AudioGenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioGenerationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AudioGenerationService/GenerateAudio',
            audio__pb2.Requirement.SerializeToString,
            audio__pb2.Audio.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
