version: "3"
services:
    client:
        build: .
        container_name: client
        networks:
            - docker_network
        volumes:
            - ./output:/output
            - ~/.cache:/root/.cache
        environment:
            - TOKEN=test
            - NODE_ADDRESS=server:50052
            - SPEAKER=v2/en_speaker_7
            - TEXT=hello
        command: python3 test.py
        # mem_limit: 6000m

networks:
    docker_network:
        driver: bridge
