version: "3"
services:
    server:
        # build:
        #     context: .
        #     dockerfile: ./cmd/fixer/Dockerfile
        image: ghcr.io/aglide100/ai-speech-server:latest
        hostname: server
        networks:
            - traefik-network
        ports:
            - 50012:50012
        environment:
            TOKEN: ${TOKEN}
            DSN: ${DSN}
networks:
    traefik-network:
        external: true
