version: "3"
services:
    server:
        image: ghcr.io/aglide100/ai-speech-server:latest
        container_name: server
        hostname: server
        networks:
            - docker_network
        volumes:
            - ~/.cache:/root/.cache
        ports:
            - 50012:50012
        environment:
            - TOKEN={TOKEN}
            - DSN={DSN}
networks:
    docker_network:
        driver: bridge
