version: "3"
services:
    server:
        build: .
        # image: ghcr.io/aglide100/ai-speech-server:latest
        container_name: server
        hostname: server
        networks:
            - docker_network
        volumes:
            - ~/.cache:/root/.cache
        ports:
            - 50012:50012
        environment:
            - TOKEN=test
            - DSN={DSN}
        command: python3 audio_server.py

networks:
    docker_network:
        driver: bridge
