version: "3"
services:
    fixer:
        # build:
        #     context: .
        #     dockerfile: ./cmd/fixer/Dockerfile
        image: ghcr.io/aglide100/ai-speech--fixer:latest
        command: "/opt/bin/fixer/main --debugMode=true"
        hostname: fixer
        networks:
            - traefik-network
        ports:
            - 50012:50012
        environment:
            TOKEN: ${TOKEN}
            DSN: ${DSN}
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 2
                failure_action: rollback
                delay: 10s
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            placement:
                constraints: [node.role==manager]
    stream:
        image: ghcr.io/aglide100/ai-speech--stream:latest
        hostname: stream
        networks:
            - traefik-network
        environment:
            TOKEN: ${TOKEN}
            DSN: ${DSN}
        deploy:
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 2
                failure_action: rollback
                delay: 10s
            restart_policy:
                condition: any
                delay: 5s
                max_attempts: 3
                window: 120s
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-network
                - traefik.http.routers.speech.rule=Host(`stream.${Domain1}`)
                - traefik.http.routers.speech.middlewares=redirect-to-https
                - traefik.http.routers.speech.entrypoints=web
                - traefik.http.services.speech.loadbalancer.server.port=9090
                - traefik.http.routers.speech--https.rule=Host(`stream.${Domain1}`)
                - traefik.http.routers.speech--https.tls=true
                - traefik.http.routers.speech--https.tls.certresolver=myresolver
                - traefik.http.routers.speech--https.entrypoints=websecure
            placement:
                constraints: [node.role==worker]

networks:
    traefik-network:
        external: true
