# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pb.svc.audio import audio_pb2 as pb_dot_svc_dot_audio_dot_audio__pb2


class AudioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAudio = channel.unary_unary(
                '/AudioService/GetAudio',
                request_serializer=pb_dot_svc_dot_audio_dot_audio__pb2.GetAudioReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_audio_dot_audio__pb2.Audio.FromString,
                )
        self.MakingNewJob = channel.unary_unary(
                '/AudioService/MakingNewJob',
                request_serializer=pb_dot_svc_dot_audio_dot_audio__pb2.MakingNewJobReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_audio_dot_audio__pb2.Error.FromString,
                )
        self.CheckingJob = channel.unary_unary(
                '/AudioService/CheckingJob',
                request_serializer=pb_dot_svc_dot_audio_dot_audio__pb2.CheckingJobReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_audio_dot_audio__pb2.CheckingJobRes.FromString,
                )
        self.SendingResult = channel.unary_unary(
                '/AudioService/SendingResult',
                request_serializer=pb_dot_svc_dot_audio_dot_audio__pb2.SendingResultReq.SerializeToString,
                response_deserializer=pb_dot_svc_dot_audio_dot_audio__pb2.Error.FromString,
                )


class AudioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakingNewJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckingJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendingResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAudio,
                    request_deserializer=pb_dot_svc_dot_audio_dot_audio__pb2.GetAudioReq.FromString,
                    response_serializer=pb_dot_svc_dot_audio_dot_audio__pb2.Audio.SerializeToString,
            ),
            'MakingNewJob': grpc.unary_unary_rpc_method_handler(
                    servicer.MakingNewJob,
                    request_deserializer=pb_dot_svc_dot_audio_dot_audio__pb2.MakingNewJobReq.FromString,
                    response_serializer=pb_dot_svc_dot_audio_dot_audio__pb2.Error.SerializeToString,
            ),
            'CheckingJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckingJob,
                    request_deserializer=pb_dot_svc_dot_audio_dot_audio__pb2.CheckingJobReq.FromString,
                    response_serializer=pb_dot_svc_dot_audio_dot_audio__pb2.CheckingJobRes.SerializeToString,
            ),
            'SendingResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SendingResult,
                    request_deserializer=pb_dot_svc_dot_audio_dot_audio__pb2.SendingResultReq.FromString,
                    response_serializer=pb_dot_svc_dot_audio_dot_audio__pb2.Error.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AudioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AudioService/GetAudio',
            pb_dot_svc_dot_audio_dot_audio__pb2.GetAudioReq.SerializeToString,
            pb_dot_svc_dot_audio_dot_audio__pb2.Audio.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MakingNewJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AudioService/MakingNewJob',
            pb_dot_svc_dot_audio_dot_audio__pb2.MakingNewJobReq.SerializeToString,
            pb_dot_svc_dot_audio_dot_audio__pb2.Error.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckingJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AudioService/CheckingJob',
            pb_dot_svc_dot_audio_dot_audio__pb2.CheckingJobReq.SerializeToString,
            pb_dot_svc_dot_audio_dot_audio__pb2.CheckingJobRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendingResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AudioService/SendingResult',
            pb_dot_svc_dot_audio_dot_audio__pb2.SendingResultReq.SerializeToString,
            pb_dot_svc_dot_audio_dot_audio__pb2.Error.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
