# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/svc/audio/audio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18pb/svc/audio/audio.proto\"\"\n\x05\x41udio\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03sec\x18\x02 \x01(\x02\"\x14\n\x05\x45rror\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\"\n\x04\x41uth\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0b\n\x03who\x18\x02 \x01(\t\"?\n\x03Job\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0f\n\x07speaker\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12\n\n\x02no\x18\x04 \x01(\x05\"%\n\x0e\x43heckingJobReq\x12\x13\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x05.Auth\":\n\x0e\x43heckingJobRes\x12\x11\n\x03job\x18\x01 \x01(\x0b\x32\x04.Job\x12\x15\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.Error\"Q\n\x10SendingResultReq\x12\x15\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x06.Audio\x12\x13\n\x04\x61uth\x18\x02 \x01(\x0b\x32\x05.Auth\x12\x11\n\x03job\x18\x03 \x01(\x0b\x32\x04.Job\"W\n\x0fMakingNewJobReq\x12\x13\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x05.Auth\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0f\n\x07speaker\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\"1\n\x0bGetAudioReq\x12\x13\n\x04\x61uth\x18\x01 \x01(\x0b\x32\x05.Auth\x12\r\n\x05jobId\x18\x02 \x01(\x05\x32\xb7\x01\n\x0c\x41udioService\x12 \n\x08GetAudio\x12\x0c.GetAudioReq\x1a\x06.Audio\x12(\n\x0cMakingNewJob\x12\x10.MakingNewJobReq\x1a\x06.Error\x12/\n\x0b\x43heckingJob\x12\x0f.CheckingJobReq\x1a\x0f.CheckingJobRes\x12*\n\rSendingResult\x12\x11.SendingResultReq\x1a\x06.ErrorB7Z5github.com/aglide100/speech-test/cluster/pb/svc/audiob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pb.svc.audio.audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z5github.com/aglide100/speech-test/cluster/pb/svc/audio'
  _globals['_AUDIO']._serialized_start=28
  _globals['_AUDIO']._serialized_end=62
  _globals['_ERROR']._serialized_start=64
  _globals['_ERROR']._serialized_end=84
  _globals['_AUTH']._serialized_start=86
  _globals['_AUTH']._serialized_end=120
  _globals['_JOB']._serialized_start=122
  _globals['_JOB']._serialized_end=185
  _globals['_CHECKINGJOBREQ']._serialized_start=187
  _globals['_CHECKINGJOBREQ']._serialized_end=224
  _globals['_CHECKINGJOBRES']._serialized_start=226
  _globals['_CHECKINGJOBRES']._serialized_end=284
  _globals['_SENDINGRESULTREQ']._serialized_start=286
  _globals['_SENDINGRESULTREQ']._serialized_end=367
  _globals['_MAKINGNEWJOBREQ']._serialized_start=369
  _globals['_MAKINGNEWJOBREQ']._serialized_end=456
  _globals['_GETAUDIOREQ']._serialized_start=458
  _globals['_GETAUDIOREQ']._serialized_end=507
  _globals['_AUDIOSERVICE']._serialized_start=510
  _globals['_AUDIOSERVICE']._serialized_end=693
# @@protoc_insertion_point(module_scope)
